### ISSUE TITLE
 Call to a member function write() on null

### ISSUE THREAD

**Issue by pvolyntsev** [valga/fbns-react#3]
## Exception
Exception 'Error' with message 'Call to a member function write() on null in /app/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php:615'

## Stack trace
```
#0 /app/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php(493): Fbns\Client\Lite\ReactMqttClient->startFlow(Object(BinSoul\Net\Mqtt\Flow\IncomingPublishFlow))
#1 /app/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php(465): Fbns\Client\Lite\ReactMqttClient->handlePacket(Object(BinSoul\Net\Mqtt\Packet\PublishRequestPacket))
#2 /app/vendor/valga/fbns-react/src/Lite/ReactMqttClient.php(391): Fbns\Client\Lite\ReactMqttClient->handleReceive('2\xAC\x04\x00\x0276*\xADx\xDA\x95R]o...')
#3 /app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Fbns\Client\Lite\ReactMqttClient->Fbns\Client\Lite\{closure}('2\xAC\x04\x00\x0276*\xADx\xDA\x95R]o...')
#4 /app/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#5 /app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('2\xAC\x04\x00\x0276*\xADx\xDA\x95R]o...')
#6 /app/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#7 [internal function]: React\Stream\DuplexResourceStream->handleData(Resource id #34791, Object(React\EventLoop\StreamSelectLoop))
#8 /app/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func(Array, Resource id #34791, Object(React\EventLoop\StreamSelectLoop))
#9 /app/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(990672)
```

### composer.json
```
{
  "require": {
        "php": ">=7.0.0",
        "ext-curl": "*",
        "ext-mbstring": "*",
        "ext-bcmath": "*",
        "react/event-loop": "^0.4.3",
        "react/promise": "^2.5",
        "react/socket": "^0.8",
        "binsoul/net-mqtt-client-react": "^0.3.2",
        "clue/socks-react": "^0.8.2",
        "clue/http-proxy-react": "^1.1.0",
        "valga/fbns-react": "^0.1.8",
    }
}
```

**Comment by pvolyntsev** [comment]
My suggestion: connection lost, need a reconnection logic
