### ISSUE TITLE
Error while registering device

### ISSUE THREAD

**Issue by d4mn** [valga/fbns-react#7]
I got this error 
`Failed to register package 'com.instagram.android': Out of bounds vec access: invalid index 1
#0 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(35): RealtimeDeliveryAuth::genSetLoginStateFromInstagramAuthToken()
#1 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(13): RealtimeDeliveryAuth::genSetAuthFromUserIDAndSessionInfo()
#2 /var/www/flib/messaging/realtime/RealtimeDeliveryHandler.php(61): RealtimeDeliveryAuth::genSetAuthFromEndpointState()
#3 /var/www/flib/__generated__/ThriftMeerkatStep/fbcode/rtgw/v2/extif/delivery.thrift/RealtimeDeliveryBackend.php(426): RealtimeDeliveryHandler->sendRealtimeDeliveryRequest()
#4 /var/www/flib/thrift/core/ThriftAsyncProcessor.php(38): RealtimeDeliveryBackendAsyncProcessorBase->process_sendRealtimeDeliveryRequest()
#5 /var/www/flib/thrift/servers/base/ThriftServer.php(364): ThriftAsyncProcessor->processAsync()
#6 /var/www/flib/alite/x/controller/thrift/XThriftControllerBaseTrait.php(41): ThriftServer->genHandleHTTPRequest()
#7 /var/www/flib/alite/x/controller/thrift/XThriftBridgeController.php(34): XThriftController->genThriftResponse()
#8 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(226): XThriftBridgeController->genResponse()
#9 /var/www/flib/attribution/AttributionEdge.php(83): Closure$ZeusGodOfThunderAlite::genMain#4()
#10 /var/www/flib/gates/turbo/context/BaseTurboGatesContext.php(262): AttributionEdge::runWithDeferredAttributionResolution()
#11 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(227): BaseTurboGatesContext->genRunWithoutCatching()
#12 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(118): ZeusGodOfThunderAlite->genMain()
#13 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(53): ZeusGodOfThunderEntryPoint::genMain()
#14 (): gen_zeusgodofthunder_main()
#15 (): Closure$__SystemLib\enter_async_entry_point()
#16 (): HH\Asio\join()
#17 (): __SystemLib\enter_async_entry_point()
#18 {main}`
My register functoion:
`$client->register(Constants::PACKAGE_NAME, Constants::FACEBOOK_ANALYTICS_APPLICATION_ID)
                    ->then(static function (Registration $registration) {
                        $this->_logger->info('Received a non-empty token.' . $registration->getToken());
                        $this->emit('fbns_token', [$registration->getToken()]);
                    })->otherwise(static function ($e) {
                        $this->_logger->error($e);
                    });`
Any ideas what can be wrong?

**Comment by valga** [comment]
@d4mn Please post full debug log, see "Enable logging to stdout" part in [Advanced Usage](https://github.com/valga/fbns-react/blob/6f64111707577f286bd625b97f64fdabb9c11bf2/README.md#advanced-usage). Log level should be set to `Logger::DEBUG`.

**Comment by d4mn** [comment]
`[2020-04-21T11:06:16.894873+03:00] ig.DEBUG: Starting push [] []
[2020-04-21T11:06:17.081045+03:00] ig.INFO: Starting FBNS client... [] []
[2020-04-21T11:06:17.264512+03:00] ig.INFO: Setting up reconnect timer to 1 seconds. [] []
[2020-04-21T11:06:18.487504+03:00] ig.INFO: Connecting to mqtt-mini.facebook.com:443... [] []
[2020-04-21T11:06:18.834159+03:00] ig.DEBUG: Network connection has been established [] []
[2020-04-21T11:06:20.128440+03:00] ig.INFO: Connected to the broker [] []
[2020-04-21T11:06:20.326838+03:00] ig.DEBUG: Setting up keepalive timer to 900 seconds [] []
[2020-04-21T11:06:20.503508+03:00] ig.INFO: Received a non-empty auth.{"ck":779143853582269,"cs":"ZSirEWaypAc0fhkqp62m1bW8g5A=","sr":1,"di":"9cc7290d-c1bf-4172-823c-0fc39e7a95af","ds":"3/mwgYxRxQhFAzsgixxjnhN7h6Q="} [] []
[2020-04-21T11:06:20.680129+03:00] ig.INFO: Trying to register package 'com.instagram.android' ["567067343352427"] []
[2020-04-21T11:06:20.869782+03:00] ig.DEBUG: Sending message to topic '/fbns_reg_req'{"pkg_name":"com.instagram.android","appid":"567067343352427"} [] []
[2020-04-21T11:06:21.054348+03:00] ig.DEBUG: Topic '/fbns_reg_req' has been mapped to '79'. [] []
[2020-04-21T11:06:21.304637+03:00] ig.DEBUG: Publish flow has been completed [] []
[2020-04-21T11:06:21.484974+03:00] ig.DEBUG: Existing keepalive timer has been canceled [] []
[2020-04-21T11:06:21.694052+03:00] ig.DEBUG: Setting up keepalive timer to 900 seconds [] []
[2020-04-21T11:06:21.877210+03:00] ig.DEBUG: Existing keepalive timer has been canceled [] []
[2020-04-21T11:06:22.053110+03:00] ig.DEBUG: Setting up keepalive timer to 900 seconds [] []
[2020-04-21T11:06:22.555240+03:00] igbot.DEBUG: ID '80' has been mapped to '/fbns_reg_resp'. [] []
[2020-04-21T11:06:22.737394+03:00] ig.DEBUG: Received a message from topic '/fbns_reg_resp' ["{\"pkg_name\":\"com.instagram.android\",\"error\":\"Out of bounds vec access: invalid index 1\\n#0 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(35): RealtimeDeliveryAuth::genSetLoginStateFromInstagramAuthToken()\\n#1 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(13): RealtimeDeliveryAuth::genSetAuthFromUserIDAndSessionInfo()\\n#2 /var/www/flib/messaging/realtime/RealtimeDeliveryHandler.php(61): RealtimeDeliveryAuth::genSetAuthFromEndpointState()\\n#3 /var/www/flib/__generated__/ThriftMeerkatStep/fbcode/rtgw/v2/extif/delivery.thrift/RealtimeDeliveryBackend.php(426): RealtimeDeliveryHandler->sendRealtimeDeliveryRequest()\\n#4 /var/www/flib/thrift/core/ThriftAsyncProcessor.php(38): RealtimeDeliveryBackendAsyncProcessorBase->process_sendRealtimeDeliveryRequest()\\n#5 /var/www/flib/thrift/servers/base/ThriftServer.php(364): ThriftAsyncProcessor->processAsync()\\n#6 /var/www/flib/alite/x/controller/thrift/XThriftControllerBaseTrait.php(41): ThriftServer->genHandleHTTPRequest()\\n#7 /var/www/flib/alite/x/controller/thrift/XThriftBridgeController.php(34): XThriftController->genThriftResponse()\\n#8 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(226): XThriftBridgeController->genResponse()\\n#9 /var/www/flib/attribution/AttributionEdge.php(83): Closure$ZeusGodOfThunderAlite::genMain#4()\\n#10 /var/www/flib/gates/turbo/context/BaseTurboGatesContext.php(262): AttributionEdge::runWithDeferredAttributionResolution()\\n#11 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(227): BaseTurboGatesContext->genRunWithoutCatching()\\n#12 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(118): ZeusGodOfThunderAlite->genMain()\\n#13 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(53): ZeusGodOfThunderEntryPoint::genMain()\\n#14 (): gen_zeusgodofthunder_main()\\n#15 (): Closure$__SystemLib\\\\enter_async_entry_point()\\n#16 (): HH\\\\Asio\\\\join()\\n#17 (): __SystemLib\\\\enter_async_entry_point()\\n#18 {main}\"}"] []
[2020-04-21T11:06:22.930258+03:00] ig.ERROR: Failed to register package 'com.instagram.android': Out of bounds vec access: invalid index 1 #0 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(35): RealtimeDeliveryAuth::genSetLoginStateFromInstagramAuthToken() #1 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(13): RealtimeDeliveryAuth::genSetAuthFromUserIDAndSessionInfo() #2 /var/www/flib/messaging/realtime/RealtimeDeliveryHandler.php(61): RealtimeDeliveryAuth::genSetAuthFromEndpointState() #3 /var/www/flib/__generated__/ThriftMeerkatStep/fbcode/rtgw/v2/extif/delivery.thrift/RealtimeDeliveryBackend.php(426): RealtimeDeliveryHandler->sendRealtimeDeliveryRequest() #4 /var/www/flib/thrift/core/ThriftAsyncProcessor.php(38): RealtimeDeliveryBackendAsyncProcessorBase->process_sendRealtimeDeliveryRequest() #5 /var/www/flib/thrift/servers/base/ThriftServer.php(364): ThriftAsyncProcessor->processAsync() #6 /var/www/flib/alite/x/controller/thrift/XThriftControllerBaseTrait.php(41): ThriftServer->genHandleHTTPRequest() #7 /var/www/flib/alite/x/controller/thrift/XThriftBridgeController.php(34): XThriftController->genThriftResponse() #8 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(226): XThriftBridgeController->genResponse() #9 /var/www/flib/attribution/AttributionEdge.php(83): Closure$ZeusGodOfThunderAlite::genMain#4() #10 /var/www/flib/gates/turbo/context/BaseTurboGatesContext.php(262): AttributionEdge::runWithDeferredAttributionResolution() #11 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(227): BaseTurboGatesContext->genRunWithoutCatching() #12 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(118): ZeusGodOfThunderAlite->genMain() #13 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(53): ZeusGodOfThunderEntryPoint::genMain() #14 (): gen_zeusgodofthunder_main() #15 (): Closure$__SystemLib\enter_async_entry_point() #16 (): HH\Asio\join() #17 (): __SystemLib\enter_async_entry_point() #18 {main} ["{\"pkg_name\":\"com.instagram.android\",\"error\":\"Out of bounds vec access: invalid index 1\\n#0 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(35): RealtimeDeliveryAuth::genSetLoginStateFromInstagramAuthToken()\\n#1 /var/www/flib/messaging/realtime/delivery/RealtimeDeliveryAuth.php(13): RealtimeDeliveryAuth::genSetAuthFromUserIDAndSessionInfo()\\n#2 /var/www/flib/messaging/realtime/RealtimeDeliveryHandler.php(61): RealtimeDeliveryAuth::genSetAuthFromEndpointState()\\n#3 /var/www/flib/__generated__/ThriftMeerkatStep/fbcode/rtgw/v2/extif/delivery.thrift/RealtimeDeliveryBackend.php(426): RealtimeDeliveryHandler->sendRealtimeDeliveryRequest()\\n#4 /var/www/flib/thrift/core/ThriftAsyncProcessor.php(38): RealtimeDeliveryBackendAsyncProcessorBase->process_sendRealtimeDeliveryRequest()\\n#5 /var/www/flib/thrift/servers/base/ThriftServer.php(364): ThriftAsyncProcessor->processAsync()\\n#6 /var/www/flib/alite/x/controller/thrift/XThriftControllerBaseTrait.php(41): ThriftServer->genHandleHTTPRequest()\\n#7 /var/www/flib/alite/x/controller/thrift/XThriftBridgeController.php(34): XThriftController->genThriftResponse()\\n#8 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(226): XThriftBridgeController->genResponse()\\n#9 /var/www/flib/attribution/AttributionEdge.php(83): Closure$ZeusGodOfThunderAlite::genMain#4()\\n#10 /var/www/flib/gates/turbo/context/BaseTurboGatesContext.php(262): AttributionEdge::runWithDeferredAttributionResolution()\\n#11 /var/www/flib/init/routing/ZeusGodOfThunderAlite.php(227): BaseTurboGatesContext->genRunWithoutCatching()\\n#12 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(118): ZeusGodOfThunderAlite->genMain()\\n#13 /var/www/flib/init/zeusgodofthunder/__entrypoint.php(53): ZeusGodOfThunderEntryPoint::genMain()\\n#14 (): gen_zeusgodofthunder_main()\\n#15 (): Closure$__SystemLib\\\\enter_async_entry_point()\\n#16 (): HH\\\\Asio\\\\join()\\n#17 (): __SystemLib\\\\enter_async_entry_point()\\n#18 {main}\"}"] []`

This error comes from IG it's self how i understand but can't get it what i'm sending wrong
P.S Using latest version 0.2.1
